/*
 Generated by Sybase Unwired Platform 
 Compiler version - 2.1.3.358
*/ 

#import "HR_SuiteSISSubscriptionKey.h"
#import "HR_SuiteSISSubscriptionKeyMetaData.h"
#import "HR_SuiteHR_SuiteDB.h"
#import "SUPClassDelegate.h"
#import "SUPEntityMetaDataRBS.h"
@implementation HR_SuiteSISSubscriptionKey

static SUPClassDelegate *g_HR_SuiteSISSubscriptionKey_delegate = nil;

+ (SUPClassDelegate *) delegate
{
	@synchronized(self) {
		if (g_HR_SuiteSISSubscriptionKey_delegate == nil) {
			g_HR_SuiteSISSubscriptionKey_delegate = [[SUPClassDelegate alloc] initWithName:@"HR_SuiteSISSubscriptionKey" clazz:[self class]
				metaData:[self metaData] dbDelegate:[HR_SuiteHR_SuiteDB delegate] database:[HR_SuiteHR_SuiteDB instance]];
		}
	}
	
	return [[g_HR_SuiteSISSubscriptionKey_delegate retain] autorelease];
}
static SUPClassMetaDataRBS* HR_SuiteSISSubscriptionKey_META_DATA;

+ (SUPClassMetaDataRBS*)metaData
{
    if (HR_SuiteSISSubscriptionKey_META_DATA == nil) {
 	   	HR_SuiteSISSubscriptionKey_META_DATA = [[HR_SuiteSISSubscriptionKeyMetaData alloc] init];
	}
	
	return HR_SuiteSISSubscriptionKey_META_DATA;
}

- (SUPClassMetaDataRBS*)getClassMetaData
{
    return [[self class] metaData];
}

@end