/*
 Generated by Sybase Unwired Platform 
 Compiler version - 2.1.3.358
*/ 

#import "HR_SuiteOfflineAuthentication.h"
#import "HR_SuiteOfflineAuthenticationMetaData.h"
#import "SUPJsonObject.h"
#import "HR_SuiteHR_SuiteDB.h"
#import "SUPLocalEntityDelegate.h"
#import "SUPEntityMetaDataRBS.h"
#import "SUPQuery.h"
#import "HR_SuiteKeyGenerator.h"
#import "HR_SuiteLocalKeyGenerator.h"
#import "HR_SuiteLogRecordImpl.h"

@implementation HR_SuiteOfflineAuthentication

@synthesize passwordHash = _passwordHash;
@synthesize user = _user;

- (NSString*)user
{
    return _user;
}

- (void)setPasswordHash:(int32_t)newPasswordHash
{
    if (newPasswordHash != self->_passwordHash)
    {
        self->_passwordHash = newPasswordHash;
        self.isDirty = YES;
    }
}

- (void)setUser:(NSString*)newUser
{
    if (newUser != self->_user)
    {
		[self->_user release];
        self->_user = [newUser retain];
        self.isNew = YES;
    }
}

static SUPLocalEntityDelegate *g_HR_SuiteOfflineAuthentication_delegate = nil;

+ (SUPLocalEntityDelegate *) delegate
{
	@synchronized(self) {
		if (g_HR_SuiteOfflineAuthentication_delegate == nil) {
			g_HR_SuiteOfflineAuthentication_delegate = [[SUPLocalEntityDelegate alloc] initWithName:@"HR_SuiteOfflineAuthentication" clazz:[self class]
				metaData:[self metaData] dbDelegate:[HR_SuiteHR_SuiteDB delegate] database:[HR_SuiteHR_SuiteDB instance]];
		}
	}
	
	return [[g_HR_SuiteOfflineAuthentication_delegate retain] autorelease];
}

static SUPEntityMetaDataRBS* HR_SuiteOfflineAuthentication_META_DATA;

+ (SUPEntityMetaDataRBS*)metaData
{
    if (HR_SuiteOfflineAuthentication_META_DATA == nil) {
		HR_SuiteOfflineAuthentication_META_DATA = [[HR_SuiteOfflineAuthenticationMetaData alloc] init];
	}
	
	return HR_SuiteOfflineAuthentication_META_DATA;
}

- (SUPClassMetaDataRBS*)getClassMetaData
{
    return [[self class] metaData];
}

- (void)clearRelationshipObjects
{
}

- (id) init
{
    if ((self = [super init]))
    {
        self.classMetaData = [HR_SuiteOfflineAuthentication metaData];
        [self setEntityDelegate:(SUPEntityDelegate*)[HR_SuiteOfflineAuthentication delegate]];
    }
    return self;    
}

- (void)dealloc
{
    if(_user)
    {
        [_user release];
        _user = nil;
    }
	[super dealloc];
}




+ (HR_SuiteOfflineAuthentication*)find:(NSString*)id_
{
    SUPObjectList *keys = [SUPObjectList getInstance];
    [keys add:id_];
    return (HR_SuiteOfflineAuthentication*)[(SUPEntityDelegate*)([[self class] delegate]) findEntityWithKeys:keys];
}

- (NSString*)_pk
{
    return (NSString*)[self i_pk];
}

+ (HR_SuiteOfflineAuthentication*)load:(NSString*)id_
{
    return (HR_SuiteOfflineAuthentication*)[(SUPEntityDelegate*)([[self class] delegate]) load:id_];
}

+ (HR_SuiteOfflineAuthentication*)getInstance
{
    HR_SuiteOfflineAuthentication* me = [[HR_SuiteOfflineAuthentication alloc] init];
    [me autorelease];
    return me;
}
- (SUPJsonObject*)getAttributeJson:(int)id_
{
    switch(id_)
    {
        default:
        return [super getAttributeJson:id_];
    }

}
- (void)setAttributeJson:(int)id_:(SUPJsonObject*)value
{
    switch(id_)
    { 
        default:
            [super setAttributeJson:id_:value];
            break;
    }

}

-(SUPString) getAttributeString:(int)id_
{
    switch(id_)
    {
    case 113:
        return self.user;
    default:
         return [super getAttributeString:id_];
    }
}

-(void) setAttributeString:(int)id_:(SUPString)v
{
    switch(id_)
    {
    case 113:
        self.user = v;
        break;;
    default:
        [super setAttributeString:id_:v];
        break;;
    }
}
-(SUPInt) getAttributeInt:(int)id_
{
    switch(id_)
    {
    case 114:
        return self.passwordHash;
    default:
         return [super getAttributeInt:id_];
    }
}

-(void) setAttributeInt:(int)id_:(SUPInt)v
{
    switch(id_)
    {
    case 114:
        self.passwordHash = v;
        break;;
    default:
        [super setAttributeInt:id_:v];
        break;;
    }
}
- (id)getAttributeLargeObject:(int)id_ loadFromDB:(BOOL)loadFromDB
{
    switch(id_)
    {
        default:
        return [super getAttributeJson:id_];
    }
}
- (void)setAttributeLargeObject:(int)id_:(id)value
{
    switch(id_)
    {
        default:
            [super setAttributeJson:id_:value];
            break;
    }

}
- (SUPObjectList*)getLogRecords
{
   return [HR_SuiteLogRecordImpl findByEntity:@"OfflineAuthentication":[self keyToString]];
}




- (NSString*)toString
{
	NSString* str = [NSString stringWithFormat:@"\
	OfflineAuthentication = \n\
	    passwordHash = %i,\n\
	    user = %@,\n\
	    isNew = %i,\n\
        isDirty = %i,\n\
        isDeleted = %i,\n\
	\n"
    	,self.passwordHash
    	,self.user
		,self.isNew
		,self.isDirty
		,self.isDeleted
	];
	return str;

}

- (NSString*)description
{
	return [self toString];
}
+ (SUPObjectList*)getPendingObjects
{
    return (SUPObjectList*)[(SUPEntityDelegate*)[[self class] delegate] getPendingObjects];
}

+ (SUPObjectList*)getPendingObjects:(int32_t)skip take:(int32_t)take
{
    return (SUPObjectList*)[(SUPEntityDelegate*)[[self class] delegate] getPendingObjects:skip:take];
}

@end