/*
 Generated by Sybase Unwired Platform 
 Compiler version - 2.1.3.358
*/ 

#import "HR_SuiteLocalKeyGenerator.h"
#import "HR_SuiteLocalKeyGeneratorMetaData.h"
#import "SUPLocalEntityDelegate.h"
#import "HR_SuiteHR_SuiteDB.h"
#import "SUPEntityDelegate.h"
#import "SUPLocalKeyGenerator.h"

@implementation HR_SuiteLocalKeyGenerator

static SUPLocalEntityDelegate *g_HR_SuiteLocalKeyGenerator_delegate = nil;

+ (SUPLocalEntityDelegate *) delegate
{
	@synchronized(self) {
		if (g_HR_SuiteLocalKeyGenerator_delegate == nil) {
			g_HR_SuiteLocalKeyGenerator_delegate = [[SUPLocalEntityDelegate alloc] initWithName:@"HR_SuiteLocalKeyGenerator" clazz:[self class]
				metaData:[self metaData] dbDelegate:[HR_SuiteHR_SuiteDB delegate] database:[HR_SuiteHR_SuiteDB instance]];
		}
	}
	
	return [[g_HR_SuiteLocalKeyGenerator_delegate retain] autorelease];
}

static SUPEntityMetaDataRBS* HR_SuiteLocalKeyGenerator_META_DATA;

+ (SUPEntityMetaDataRBS*)metaData
{
    if (HR_SuiteLocalKeyGenerator_META_DATA == nil) {
 	   	HR_SuiteLocalKeyGenerator_META_DATA = [[HR_SuiteLocalKeyGeneratorMetaData alloc] init];
	}
	
	return HR_SuiteLocalKeyGenerator_META_DATA;
}

- (SUPClassMetaDataRBS*)getClassMetaData
{
    return [[self class] metaData];
}

- (id)init
{
    self = [super initWithParameters:[HR_SuiteHR_SuiteDB delegate]:@"co_hr_suite_1_0_localkeygenerator":100000];
    if (self) {
        // Initialization code here.
        [SUPLocalKeyGenerator setObjectInstance:@"HR_Suite":self];
    }
    
    return self;
}

+ (HR_SuiteLocalKeyGenerator*)getInstance
{
    HR_SuiteLocalKeyGenerator* me = [[HR_SuiteLocalKeyGenerator alloc] init];
    [me autorelease];
    return me;
}

+ (int64_t)generateId
{
    return [[HR_SuiteHR_SuiteDB delegate] generateLocalId];
}

@end