/*
 Generated by Sybase Unwired Platform 
 Compiler version - 2.1.3.358
*/ 

#import "HR_SuitePersonalizationParameters.h"
#import "HR_SuitePersonalizationParametersMetaData.h"
#import "SUPJsonObject.h"
#import "HR_SuiteHR_SuiteDB.h"
#import "SUPClassDelegate.h"
#import "SUPJsonReader.h"
#import "SUPEntityMetaDataRBS.h"

@interface HR_SuitePersonalizationParameters(hidden)
-(void)submitPending;
@end
@implementation HR_SuitePersonalizationParameters

@synthesize username = _username;
@synthesize usernameUserDefined = _usernameUserDefined;
@synthesize password = _password;
@synthesize passwordUserDefined = _passwordUserDefined;

- (void)setUsername:(NSString*)newUsername
{
    if (newUsername != self->_username)
    {
		[self->_username release];
        self->_username = [newUsername retain];
		_usernameUserDefined = YES;
    }
}
- (void)setUsernameUserDefined:(BOOL)newUsernameUserDefined
{
    if (newUsernameUserDefined != self->_usernameUserDefined)
    {
        self->_usernameUserDefined = newUsernameUserDefined;
    }
}
- (void)setPassword:(NSString*)newPassword
{
    if (newPassword != self->_password)
    {
		[self->_password release];
        self->_password = [newPassword retain];
		_passwordUserDefined = YES;
    }
}
- (void)setPasswordUserDefined:(BOOL)newPasswordUserDefined
{
    if (newPasswordUserDefined != self->_passwordUserDefined)
    {
        self->_passwordUserDefined = newPasswordUserDefined;
    }
}

static SUPClassDelegate *g_HR_SuitePersonalizationParameters_delegate = nil;

+ (SUPClassDelegate *) delegate
{
	@synchronized(self) {
		if (g_HR_SuitePersonalizationParameters_delegate == nil) {
			g_HR_SuitePersonalizationParameters_delegate = [[SUPClassDelegate alloc] initWithName:@"HR_SuitePersonalizationParameters" clazz:[self class]
				metaData:[self metaData] dbDelegate:[HR_SuiteHR_SuiteDB delegate] database:[HR_SuiteHR_SuiteDB instance]];
		}
	}
	
	return [[g_HR_SuitePersonalizationParameters_delegate retain] autorelease];
}

- (SUPJsonObject*)getAttributeJson:(int)id_
{
    switch(id_)
    {
        default:
        return [super getAttributeJson:id_];
    }

}
- (void)setAttributeJson:(int)id_:(SUPJsonObject*)value
{
    switch(id_)
    { 
        default:
            [super setAttributeJson:id_:value];
            break;
    }

}
static SUPClassMetaDataRBS* HR_SuitePersonalizationParameters_META_DATA;

+ (SUPClassMetaDataRBS*)metaData
{
    if (HR_SuitePersonalizationParameters_META_DATA == nil) {
 	   	HR_SuitePersonalizationParameters_META_DATA = [[HR_SuitePersonalizationParametersMetaData alloc] init];
	}
	
	return HR_SuitePersonalizationParameters_META_DATA;
}

- (SUPClassMetaDataRBS*)getClassMetaData
{
    return [[self class] metaData];
}
- (id) init
{
    if ((self = [super init]))
    {
        self.classMetaData = (SUPEntityMetaDataRBS *)[HR_SuitePersonalizationParameters metaData];
        [self setClassDelegate:[[self class] delegate]];
        _usernameUserDefined = NO;
        _passwordUserDefined = NO;   
        clientPersonalizationTableName = @"co_hr_suite_1_0_clientpersonalization";
        [self load];
        
    }
    return self;    
}

-(SUPString) getAttributeString:(int)id_
{
    switch(id_)
    {
    case 128:
        return self.username;
    case 130:
        return self.password;
    default:
        return [super getAttributeString:id_];
    }
}

-(void) setAttributeString:(int)id_:(SUPString)v
{
    switch(id_)
    {
    case 128:
        self.username = v;
        break;;
    case 130:
        self.password = v;
        break;;
    default:
        [super setAttributeString:id_:v];
        break;;
    }
}
-(SUPBoolean) getAttributeBoolean:(int)id_
{
    switch(id_)
    {
    case 129:
        return self.usernameUserDefined;
    case 131:
        return self.passwordUserDefined;
    default:
        return [super getAttributeBoolean:id_];
    }
}

-(void) setAttributeBoolean:(int)id_:(SUPBoolean)v
{
    switch(id_)
    {
    case 129:
        self.usernameUserDefined = v;
        break;;
    case 131:
        self.passwordUserDefined = v;
        break;;
    default:
        [super setAttributeBoolean:id_:v];
        break;;
    }
}
- (id)getAttributeLargeObject:(int)id_ loadFromDB:(BOOL)loadFromDB
{
    switch(id_)
    {
        default:
        return [super getAttributeJson:id_];
    }
}
- (void)setAttributeLargeObject:(int)id_:(id)value
{
    switch(id_)
    {
        default:
            [super setAttributeJson:id_:value];
            break;
    }

}
+ (HR_SuitePersonalizationParameters*)getInstance
{
    HR_SuitePersonalizationParameters* me = [[HR_SuitePersonalizationParameters alloc] init];
    [me autorelease];
    return me;
}
- (void)dealloc
{
    if(_username)
    {
        [_username release];
        _username = nil;
    }
    if(_password)
    {
        [_password release];
        _password = nil;
    }
	[super dealloc];
}

@end