/*
 Generated by Sybase Unwired Platform 
 Compiler version - 2.1.3.358
*/ 

#import "HR_SuiteSISSubscription.h"
#import "HR_SuiteSISSubscriptionMetaData.h"
#import "HR_SuiteHR_SuiteDB.h"
#import "SUPEntityDelegate.h"
#import "SUPEntityMetaDataRBS.h"
@implementation HR_SuiteSISSubscription

static SUPEntityDelegate *g_HR_SuiteSISSubscription_delegate = nil;

+ (SUPEntityDelegate *) delegate
{
	@synchronized(self) {
		if (g_HR_SuiteSISSubscription_delegate == nil) {
			g_HR_SuiteSISSubscription_delegate = [[SUPEntityDelegate alloc] initWithName:@"HR_SuiteSISSubscription" clazz:[self class]
				metaData:[self metaData] dbDelegate:[HR_SuiteHR_SuiteDB delegate] database:[HR_SuiteHR_SuiteDB instance]];
		}
	}
	
	return [[g_HR_SuiteSISSubscription_delegate retain] autorelease];
}

static SUPEntityMetaDataRBS* HR_SuiteSISSubscription_META_DATA;

+ (SUPEntityMetaDataRBS*)metaData
{
    if (HR_SuiteSISSubscription_META_DATA == nil) {
		HR_SuiteSISSubscription_META_DATA = [[HR_SuiteSISSubscriptionMetaData alloc] init];
	}
	
	return HR_SuiteSISSubscription_META_DATA;
}

- (SUPClassMetaDataRBS*)getClassMetaData
{
    return [[self class] metaData];
}

- (void)clearRelationshipObjects
{
}

@end