#import "sybase_sup.h"

#import "SUPClassWithMetaData.h"
#import "SUPAbstractPersonalizationParameters.h"


@class SUPClassDelegate;
@class SUPClassMetaDataRBS;

// public interface declaration, can be used by application. 
/*!
 @class HR_SuitePersonalizationParameters
 @abstract This class is part of package "HR_Suite:1.0"
 @discussion Generated by Sybase Unwired Platform, compiler version 2.1.3.358
*/

@interface HR_SuitePersonalizationParameters : SUPAbstractPersonalizationParameters<SUPClassWithMetaData>
{
@private
    NSString* _username;
    BOOL _usernameUserDefined;
    NSString* _password;
    BOOL _passwordUserDefined;
}

@property(retain,nonatomic) NSString* username;
@property(assign,nonatomic) BOOL usernameUserDefined;
@property(retain,nonatomic) NSString* password;
@property(assign,nonatomic) BOOL passwordUserDefined;

- (id) init;
- (void)dealloc;
/*!
  @method 
  @abstract Creates a new autoreleased instance of this class
  @discussion
 */
+ (HR_SuitePersonalizationParameters*)getInstance;
+ (SUPClassDelegate *)delegate;
+ (SUPClassMetaDataRBS*)metaData;
- (SUPClassMetaDataRBS*)getClassMetaData;


@end
typedef SUPObjectList HR_SuitePersonalizationParametersList;

// internal methods declaration, only used by generated code.
@interface HR_SuitePersonalizationParameters(internal)


- (SUPJsonObject*)getAttributeJson:(int)id_;
- (void)setAttributeJson:(int)id_:(SUPJsonObject*)value;

-(SUPString) getAttributeString:(int)id_;
-(void) setAttributeString:(int)id_:(SUPString)v;
-(SUPBoolean) getAttributeBoolean:(int)id_;
-(void) setAttributeBoolean:(int)id_:(SUPBoolean)v;
@end