#import "SUPAbstractLogger.h"

/*!
 @class HR_SuiteLoggerImpl
 @abstract This class is part of package "HR_Suite:1.0"
 @discussion Generated by Sybase Unwired Platform, compiler version 2.1.3.358
*/ 

@interface HR_SuiteLoggerImpl: SUPAbstractLogger

@end