#import "sybase_sup.h"

#import "SUPClassWithMetaData.h"
#import "SUPSISSubscriptionKey.h"


@class SUPClassDelegate;
@class SUPClassMetaDataRBS;

// public interface declaration, can be used by application. 
/*!
 @class HR_SuiteSISSubscriptionKey
 @abstract This class is part of package "HR_Suite:1.0"
 @discussion Generated by Sybase Unwired Platform, compiler version 2.1.3.358
*/

@interface HR_SuiteSISSubscriptionKey : SUPSISSubscriptionKey<SUPClassWithMetaData>
{
}
+ (SUPClassDelegate *)delegate;
+ (SUPClassMetaDataRBS*)metaData;
- (SUPClassMetaDataRBS*)getClassMetaData;


@end