#import "sybase_sup.h"
#import "SUPLocalKeyGenerator.h"
#import "SUPKeyGeneratorPK.h"
#import "SUPClassWithMetaData.h"

@class SUPEntityMetaDataRBS;
@protocol SUPClassWithMetaData;
@class SUPLocalEntityDelegate;
@class SUPClassMetaDataRBS;
@class HR_SuiteLocalKeyGeneratorPK;

// public interface declaration, can be used by application.
/*!
 @class HR_SuiteLocalKeyGenerator
 @abstract This class is part of package "HR_Suite:1.0"
 @discussion Generated by Sybase Unwired Platform, compiler version 2.1.3.358
*/

@interface HR_SuiteLocalKeyGenerator : SUPLocalKeyGenerator<SUPClassWithMetaData>
{
}
+ (SUPLocalEntityDelegate *)delegate;
+ (SUPEntityMetaDataRBS*)metaData;
/*!
  @method 
  @abstract Creates a new autoreleased instance of this class
  @discussion
 */
+ (HR_SuiteLocalKeyGenerator*)getInstance;
- (SUPClassMetaDataRBS*)getClassMetaData;
+ (int64_t) generateId;


@end